/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

module all_logic(g_input, e_input, o);
  input [10:0] g_input;
  input [9:0] e_input;
  output [10:0] o;
  
  AND _0_ (
    .A(g_input[0]),
    .B(e_input[0]),
    .Z(o[0])
  );
  
  ANDN _1_ (
    .A(g_input[1]),
    .B(e_input[1]),
    .Z(o[1])
  );
  
  XOR _2_ (
    .A(g_input[2]),
    .B(e_input[2]),
    .Z(o[2])
  );
  
  NAND _3_ (
    .A(g_input[3]),
    .B(e_input[3]),
    .Z(o[3])
  );
  
  NANDN _4_ (
    .A(g_input[4]),
    .B(e_input[4]),
    .Z(o[4])
  );
  
  XNOR _5_ (
    .A(g_input[5]),
    .B(e_input[5]),
    .Z(o[5])
  );
  
  OR _6_ (
    .A(g_input[6]),
    .B(e_input[6]),
    .Z(o[6])
  );
  
  ORN _7_ (
    .A(g_input[7]),
    .B(e_input[7]),
    .Z(o[7])
  );
  
  IV _8_ (
    .A(g_input[8]),
    .Z(o[8])
  );
  
  NOR _9_ (
    .A(g_input[9]),
    .B(e_input[8]),
    .Z(o[9])
  );
  
  NORN _10_ (
    .A(g_input[10]),
    .B(e_input[9]),
    .Z(o[10])
  );
  
endmodule
