/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

module mix_logic(g_input, e_input, o);
  input [2:0] g_input;
  input [1:0] e_input;
  output [1:0] o;
  
  wire w0, w1, w2, w3, w4, w5;
  
  AND _0_ (
    .A(g_input[0]),
    .B(e_input[0]),
    .Z(w0)
  );
  
  OR _1_ (
    .A(g_input[0]),
    .B(e_input[0]),
    .Z(w1)
  );
  
  XOR _3_ (
    .A(g_input[1]),
    .B(e_input[1]),
    .Z(w2)
  );
  
  NOR _4_ (
    .A(e_input[0]),
    .B(w2),
    .Z(w4)
  );
  
  NAND _5_ (
    .A(e_input[1]),
    .B(g_input[2]),
    .Z(w3)
  );
  
  XOR _6_ (
    .A(w0),
    .B(w1),
    .Z(w5)
  );  
  
  IV _7_ (
    .A(w5),
    .Z(o[0])
  );
  
  ANDN _8_ (
    .A(w3),
    .B(w4),
    .Z(o[1])
  ); 
  
  
endmodule
